name: Feature request
description: Suggest an idea for this project
labels: [enhancement, triage]
body:
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: What problem does this feature solve?
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Please describe your proposed solution in detail.
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other solutions or features have you considered?
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched the [issue tracker](../) for a similar feature.
