name: Question
description: Ask a question about usage, integration, or development.
labels: [question, triage]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Ask your question in as much detail as possible.
      required: true
  - type: input
    id: env
    attributes:
      label: Your Flutter & Dart version
      required: false
